on: push

jobs:
  deployment:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: cPanel autopull
      env:
        api_key: ${{ secrets.CPANEL_API_KEY }}
      uses: fjogeleit/http-request-action@v1.14.1
      with:
        url: 'https://cp05.azehosting.net:2083/$api_key/execute/VersionControl/update?repository_root=/home/nettelfi/public_html&branch=main'
        method: 'GET'
